-- BJStock Phase 1 — initial business schema
-- Laboratory PostgreSQL only. Android runtime remains Room / SQLite.
--
-- Design rules applied:
-- - No PostgreSQL ENUM (TEXT + CHECK)
-- - No JSONB business columns (AI payloads are TEXT)
-- - No ARRAY, generated columns, or complex triggers
-- - TIMESTAMPTZ stored in UTC; trade/evaluation dates are DATE
-- - Financial amounts use NUMERIC, never FLOAT/REAL
-- - FK default: ON DELETE RESTRICT
-- - Exception: stock_evaluation_details.evaluation_id ON DELETE CASCADE

SET search_path TO bjstock, public;

-- ---------------------------------------------------------------------------
-- instruments
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.instruments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market          TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    name            TEXT NOT NULL,
    sector          TEXT,
    industry        TEXT,
    currency        TEXT NOT NULL DEFAULT 'KRW',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    listed_date     DATE,
    delisted_date   DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_instruments_market_symbol UNIQUE (market, symbol),
    CONSTRAINT ck_instruments_market_not_empty CHECK (market <> ''),
    CONSTRAINT ck_instruments_symbol_not_empty CHECK (symbol <> ''),
    CONSTRAINT ck_instruments_name_not_empty CHECK (name <> ''),
    CONSTRAINT ck_instruments_currency_not_empty CHECK (currency <> ''),
    CONSTRAINT ck_instruments_delisted_after_listed
        CHECK (delisted_date IS NULL OR listed_date IS NULL OR delisted_date >= listed_date)
);

COMMENT ON TABLE bjstock.instruments IS
    'Listed tradable instruments. Unique by market + symbol.';
COMMENT ON COLUMN bjstock.instruments.market IS
    'Exchange or market code, e.g. KRX.';
COMMENT ON COLUMN bjstock.instruments.symbol IS
    'Market-local ticker, e.g. 005930.';

-- ---------------------------------------------------------------------------
-- market_daily_bars
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.market_daily_bars (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id   BIGINT NOT NULL,
    trade_date      DATE NOT NULL,
    open_price      NUMERIC(18, 4) NOT NULL,
    high_price      NUMERIC(18, 4) NOT NULL,
    low_price       NUMERIC(18, 4) NOT NULL,
    close_price     NUMERIC(18, 4) NOT NULL,
    volume          BIGINT NOT NULL,
    trading_value   NUMERIC(20, 4),
    source          TEXT NOT NULL,
    collected_at    TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_market_daily_bars_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES bjstock.instruments (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_market_daily_bars_instrument_trade_date
        UNIQUE (instrument_id, trade_date),
    CONSTRAINT ck_market_daily_bars_open_price_nonneg CHECK (open_price >= 0),
    CONSTRAINT ck_market_daily_bars_high_price_nonneg CHECK (high_price >= 0),
    CONSTRAINT ck_market_daily_bars_low_price_nonneg CHECK (low_price >= 0),
    CONSTRAINT ck_market_daily_bars_close_price_nonneg CHECK (close_price >= 0),
    CONSTRAINT ck_market_daily_bars_volume_nonneg CHECK (volume >= 0),
    CONSTRAINT ck_market_daily_bars_trading_value_nonneg
        CHECK (trading_value IS NULL OR trading_value >= 0),
    CONSTRAINT ck_market_daily_bars_high_gte_low CHECK (high_price >= low_price),
    CONSTRAINT ck_market_daily_bars_source_not_empty CHECK (source <> '')
);

COMMENT ON TABLE bjstock.market_daily_bars IS
    'Daily OHLCV bars. UNIQUE(instrument_id, trade_date) also covers latest-bar lookups.';
COMMENT ON COLUMN bjstock.market_daily_bars.open_price IS
    'NUMERIC money/price. Never FLOAT/REAL.';

-- ---------------------------------------------------------------------------
-- factor_definitions
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.factor_definitions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factor_code         TEXT NOT NULL,
    factor_name         TEXT NOT NULL,
    category            TEXT NOT NULL,
    description         TEXT,
    value_type          TEXT NOT NULL,
    higher_is_better    BOOLEAN NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_factor_definitions_factor_code UNIQUE (factor_code),
    CONSTRAINT ck_factor_definitions_code_not_empty CHECK (factor_code <> ''),
    CONSTRAINT ck_factor_definitions_name_not_empty CHECK (factor_name <> ''),
    CONSTRAINT ck_factor_definitions_value_type_not_empty CHECK (value_type <> ''),
    CONSTRAINT ck_factor_definitions_category
        CHECK (category IN (
            'FINANCIAL',
            'VALUATION',
            'MOMENTUM',
            'VOLUME',
            'FLOW',
            'MARKET',
            'TECHNICAL',
            'OTHER'
        ))
);

COMMENT ON TABLE bjstock.factor_definitions IS
    'Named factor catalog. category/value_type are TEXT + CHECK, not ENUM.';
COMMENT ON COLUMN bjstock.factor_definitions.value_type IS
    'Open vocabulary in Phase 1 (non-empty TEXT). Closed set deferred to Factor Engine.';

-- ---------------------------------------------------------------------------
-- factor_values
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.factor_values (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id           BIGINT NOT NULL,
    factor_id               BIGINT NOT NULL,
    evaluation_date         DATE NOT NULL,
    raw_value               NUMERIC(20, 8),
    normalized_score        NUMERIC(7, 4),
    source                  TEXT NOT NULL,
    calculation_version     TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_factor_values_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES bjstock.instruments (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_factor_values_factor
        FOREIGN KEY (factor_id)
        REFERENCES bjstock.factor_definitions (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_factor_values_instrument_factor_date_version
        UNIQUE (instrument_id, factor_id, evaluation_date, calculation_version),
    CONSTRAINT ck_factor_values_normalized_score
        CHECK (
            normalized_score IS NULL
            OR (normalized_score >= 0 AND normalized_score <= 100)
        ),
    CONSTRAINT ck_factor_values_source_not_empty CHECK (source <> ''),
    CONSTRAINT ck_factor_values_calc_version_not_empty CHECK (calculation_version <> '')
);

COMMENT ON TABLE bjstock.factor_values IS
    'Computed factor outputs. Store raw_value and normalized_score together when possible.';

CREATE INDEX idx_factor_values_instrument_eval_date
    ON bjstock.factor_values (instrument_id, evaluation_date DESC);

CREATE INDEX idx_factor_values_factor_eval_date
    ON bjstock.factor_values (factor_id, evaluation_date DESC);

-- ---------------------------------------------------------------------------
-- strategies
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.strategies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_code   TEXT NOT NULL,
    strategy_name   TEXT NOT NULL,
    description     TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_strategies_strategy_code UNIQUE (strategy_code),
    CONSTRAINT ck_strategies_code_not_empty CHECK (strategy_code <> ''),
    CONSTRAINT ck_strategies_name_not_empty CHECK (strategy_name <> '')
);

COMMENT ON TABLE bjstock.strategies IS
    'Logical strategy identity. Concrete settings live on strategy_versions.';

-- ---------------------------------------------------------------------------
-- strategy_versions
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.strategy_versions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id     BIGINT NOT NULL,
    version_no      INTEGER NOT NULL,
    description     TEXT,
    buy_threshold   NUMERIC(7, 4) NOT NULL,
    sell_threshold  NUMERIC(7, 4) NOT NULL,
    valid_from      DATE,
    valid_to        DATE,
    status          TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_strategy_versions_strategy
        FOREIGN KEY (strategy_id)
        REFERENCES bjstock.strategies (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_strategy_versions_strategy_version UNIQUE (strategy_id, version_no),
    CONSTRAINT ck_strategy_versions_version_no CHECK (version_no >= 1),
    CONSTRAINT ck_strategy_versions_buy_threshold
        CHECK (buy_threshold >= 0 AND buy_threshold <= 100),
    CONSTRAINT ck_strategy_versions_sell_threshold
        CHECK (sell_threshold >= 0 AND sell_threshold <= 100),
    CONSTRAINT ck_strategy_versions_valid_range
        CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_strategy_versions_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED'))
);

COMMENT ON TABLE bjstock.strategy_versions IS
    'Immutable-in-practice settings once a version is used in a forward test.';

-- ---------------------------------------------------------------------------
-- strategy_factor_weights
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.strategy_factor_weights (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_version_id     BIGINT NOT NULL,
    factor_id               BIGINT NOT NULL,
    weight                  NUMERIC(8, 6) NOT NULL,
    min_score               NUMERIC(7, 4),
    max_score               NUMERIC(7, 4),
    enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_strategy_factor_weights_version
        FOREIGN KEY (strategy_version_id)
        REFERENCES bjstock.strategy_versions (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_strategy_factor_weights_factor
        FOREIGN KEY (factor_id)
        REFERENCES bjstock.factor_definitions (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_strategy_factor_weights_version_factor
        UNIQUE (strategy_version_id, factor_id),
    CONSTRAINT ck_strategy_factor_weights_weight
        CHECK (weight >= 0 AND weight <= 1),
    CONSTRAINT ck_strategy_factor_weights_min_score
        CHECK (min_score IS NULL OR (min_score >= 0 AND min_score <= 100)),
    CONSTRAINT ck_strategy_factor_weights_max_score
        CHECK (max_score IS NULL OR (max_score >= 0 AND max_score <= 100)),
    CONSTRAINT ck_strategy_factor_weights_score_range
        CHECK (min_score IS NULL OR max_score IS NULL OR min_score <= max_score)
);

COMMENT ON TABLE bjstock.strategy_factor_weights IS
    'Per-version factor weights. SUM(enabled weight)=1.0 is verified by SQL, not a trigger.';

-- ---------------------------------------------------------------------------
-- strategy_runs
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.strategy_runs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_name                TEXT NOT NULL,
    strategy_version_id     BIGINT NOT NULL,
    run_type                TEXT NOT NULL DEFAULT 'PAPER',
    start_date              DATE NOT NULL,
    end_date                DATE,
    initial_cash            NUMERIC(20, 4) NOT NULL,
    status                  TEXT NOT NULL,
    started_at              TIMESTAMPTZ,
    ended_at                TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_strategy_runs_strategy_version
        FOREIGN KEY (strategy_version_id)
        REFERENCES bjstock.strategy_versions (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_strategy_runs_name_not_empty CHECK (run_name <> ''),
    CONSTRAINT ck_strategy_runs_run_type CHECK (run_type IN ('PAPER')),
    CONSTRAINT ck_strategy_runs_initial_cash CHECK (initial_cash > 0),
    CONSTRAINT ck_strategy_runs_date_range
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_strategy_runs_status
        CHECK (status IN ('DRAFT', 'READY', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED'))
);

COMMENT ON TABLE bjstock.strategy_runs IS
    'Independent forward-test unit: one strategy version, period, and virtual cash book.';
COMMENT ON COLUMN bjstock.strategy_runs.run_type IS
    'Phase 1 allows PAPER only. Additional types require a later CHECK migration.';
COMMENT ON COLUMN bjstock.strategy_runs.initial_cash IS
    'Starting virtual cash. This run is the virtual-account unit; there is no trading_accounts table.';

CREATE INDEX idx_strategy_runs_strategy_version
    ON bjstock.strategy_runs (strategy_version_id);

-- ---------------------------------------------------------------------------
-- stock_evaluations
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.stock_evaluations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id     BIGINT NOT NULL,
    instrument_id       BIGINT NOT NULL,
    evaluation_date     DATE NOT NULL,
    quant_score         NUMERIC(7, 4) NOT NULL,
    ai_score            NUMERIC(7, 4),
    final_score         NUMERIC(7, 4) NOT NULL,
    quant_decision      TEXT NOT NULL,
    final_decision      TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_evaluations_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_stock_evaluations_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES bjstock.instruments (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_stock_evaluations_run_instrument_date
        UNIQUE (strategy_run_id, instrument_id, evaluation_date),
    CONSTRAINT ck_stock_evaluations_quant_score
        CHECK (quant_score >= 0 AND quant_score <= 100),
    CONSTRAINT ck_stock_evaluations_ai_score
        CHECK (ai_score IS NULL OR (ai_score >= 0 AND ai_score <= 100)),
    CONSTRAINT ck_stock_evaluations_final_score
        CHECK (final_score >= 0 AND final_score <= 100),
    CONSTRAINT ck_stock_evaluations_quant_decision
        CHECK (quant_decision IN ('BUY', 'HOLD', 'SELL', 'NO_ACTION')),
    CONSTRAINT ck_stock_evaluations_final_decision
        CHECK (final_decision IN ('BUY', 'HOLD', 'SELL', 'NO_ACTION'))
);

COMMENT ON TABLE bjstock.stock_evaluations IS
    'Official daily evaluation per run/instrument. Quant and final decisions are stored separately.';

CREATE INDEX idx_stock_evaluations_run_eval_date
    ON bjstock.stock_evaluations (strategy_run_id, evaluation_date DESC);

CREATE INDEX idx_stock_evaluations_instrument_eval_date
    ON bjstock.stock_evaluations (instrument_id, evaluation_date DESC);

-- ---------------------------------------------------------------------------
-- stock_evaluation_details
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.stock_evaluation_details (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id   BIGINT NOT NULL,
    factor_id       BIGINT NOT NULL,
    raw_value       NUMERIC(20, 8),
    factor_score    NUMERIC(7, 4) NOT NULL,
    weight          NUMERIC(8, 6) NOT NULL,
    weighted_score  NUMERIC(12, 8) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_evaluation_details_evaluation
        FOREIGN KEY (evaluation_id)
        REFERENCES bjstock.stock_evaluations (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_stock_evaluation_details_factor
        FOREIGN KEY (factor_id)
        REFERENCES bjstock.factor_definitions (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_stock_evaluation_details_evaluation_factor
        UNIQUE (evaluation_id, factor_id),
    CONSTRAINT ck_stock_evaluation_details_factor_score
        CHECK (factor_score >= 0 AND factor_score <= 100),
    CONSTRAINT ck_stock_evaluation_details_weight
        CHECK (weight >= 0 AND weight <= 1)
);

COMMENT ON TABLE bjstock.stock_evaluation_details IS
    'Per-factor contribution for an evaluation. Child-only rows; CASCADE delete with parent.';
COMMENT ON CONSTRAINT fk_stock_evaluation_details_evaluation ON bjstock.stock_evaluation_details IS
    'CASCADE: details have no independent audit value without the parent evaluation.';

-- ---------------------------------------------------------------------------
-- positions
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.positions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id     BIGINT NOT NULL,
    instrument_id       BIGINT NOT NULL,
    quantity            NUMERIC(20, 4) NOT NULL,
    average_price       NUMERIC(18, 4) NOT NULL,
    realized_profit     NUMERIC(20, 4) NOT NULL DEFAULT 0,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_positions_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_positions_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES bjstock.instruments (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_positions_run_instrument UNIQUE (strategy_run_id, instrument_id),
    CONSTRAINT ck_positions_quantity_nonneg CHECK (quantity >= 0),
    CONSTRAINT ck_positions_average_price_nonneg CHECK (average_price >= 0)
);

COMMENT ON TABLE bjstock.positions IS
    'Current-position projection for fast lookup. Not the ledger source of truth.';
COMMENT ON COLUMN bjstock.positions.quantity IS
    'Current holdings cache. Reconstruct P&L from orders/executions, not from this row alone.';

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_order_id     TEXT NOT NULL,
    strategy_run_id     BIGINT NOT NULL,
    instrument_id       BIGINT NOT NULL,
    evaluation_id       BIGINT,
    side                TEXT NOT NULL,
    order_type          TEXT NOT NULL,
    requested_price     NUMERIC(18, 4),
    quantity            NUMERIC(20, 4) NOT NULL,
    status              TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    executed_at         TIMESTAMPTZ,
    cancelled_at        TIMESTAMPTZ,
    CONSTRAINT uq_orders_client_order_id UNIQUE (client_order_id),
    CONSTRAINT fk_orders_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orders_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES bjstock.instruments (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orders_evaluation
        FOREIGN KEY (evaluation_id)
        REFERENCES bjstock.stock_evaluations (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_orders_client_order_id_not_empty CHECK (client_order_id <> ''),
    CONSTRAINT ck_orders_side CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_orders_order_type CHECK (order_type IN ('MARKET', 'LIMIT')),
    CONSTRAINT ck_orders_requested_price_nonneg
        CHECK (requested_price IS NULL OR requested_price >= 0),
    CONSTRAINT ck_orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_orders_status
        CHECK (status IN ('CREATED', 'VIRTUAL_FILLED', 'CANCELLED', 'REJECTED'))
);

COMMENT ON TABLE bjstock.orders IS
    'Virtual orders for paper trading. evaluation_id is nullable to allow future manual virtual orders.';
COMMENT ON COLUMN bjstock.orders.client_order_id IS
    'Portable UUID string (TEXT), not PostgreSQL UUID type.';

CREATE INDEX idx_orders_run_created
    ON bjstock.orders (strategy_run_id, created_at DESC);

CREATE INDEX idx_orders_instrument_created
    ON bjstock.orders (instrument_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- executions
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.executions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT NOT NULL,
    execution_price     NUMERIC(18, 4) NOT NULL,
    quantity            NUMERIC(20, 4) NOT NULL,
    commission          NUMERIC(20, 4) NOT NULL DEFAULT 0,
    tax                 NUMERIC(20, 4) NOT NULL DEFAULT 0,
    slippage            NUMERIC(18, 4) NOT NULL DEFAULT 0,
    executed_at         TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_executions_order
        FOREIGN KEY (order_id)
        REFERENCES bjstock.orders (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_executions_price_nonneg CHECK (execution_price >= 0),
    CONSTRAINT ck_executions_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_executions_commission_nonneg CHECK (commission >= 0),
    CONSTRAINT ck_executions_tax_nonneg CHECK (tax >= 0)
);

COMMENT ON TABLE bjstock.executions IS
    'Fill history. Together with orders this is the trading ledger source of truth.';

CREATE INDEX idx_executions_order_id
    ON bjstock.executions (order_id);

-- ---------------------------------------------------------------------------
-- portfolio_daily_snapshots
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.portfolio_daily_snapshots (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id         BIGINT NOT NULL,
    snapshot_date           DATE NOT NULL,
    cash                    NUMERIC(20, 4) NOT NULL,
    market_value            NUMERIC(20, 4) NOT NULL,
    total_asset             NUMERIC(20, 4) NOT NULL,
    daily_profit            NUMERIC(20, 4) NOT NULL,
    daily_return            NUMERIC(12, 8) NOT NULL,
    cumulative_profit       NUMERIC(20, 4) NOT NULL,
    cumulative_return       NUMERIC(12, 8) NOT NULL,
    drawdown                NUMERIC(12, 8) NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_portfolio_daily_snapshots_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_portfolio_daily_snapshots_run_date
        UNIQUE (strategy_run_id, snapshot_date)
);

COMMENT ON TABLE bjstock.portfolio_daily_snapshots IS
    'Daily virtual-portfolio snapshot used for return, MDD, and benchmark analytics.';
COMMENT ON CONSTRAINT uq_portfolio_daily_snapshots_run_date ON bjstock.portfolio_daily_snapshots IS
    'Also used as the (strategy_run_id, snapshot_date) lookup index, including DESC scans.';

-- ---------------------------------------------------------------------------
-- ai_advice_requests
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.ai_advice_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id       BIGINT NOT NULL,
    provider            TEXT NOT NULL,
    model               TEXT NOT NULL,
    prompt_version      TEXT NOT NULL,
    request_payload     TEXT,
    requested_at        TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_advice_requests_evaluation
        FOREIGN KEY (evaluation_id)
        REFERENCES bjstock.stock_evaluations (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_ai_advice_requests_provider_not_empty CHECK (provider <> ''),
    CONSTRAINT ck_ai_advice_requests_model_not_empty CHECK (model <> ''),
    CONSTRAINT ck_ai_advice_requests_prompt_version_not_empty CHECK (prompt_version <> '')
);

COMMENT ON TABLE bjstock.ai_advice_requests IS
    'Optional AI advisory request history. Never store API keys or secrets.';
COMMENT ON COLUMN bjstock.ai_advice_requests.request_payload IS
    'Serialized TEXT (JSON-as-text allowed). Not a JSONB domain column.';

CREATE INDEX idx_ai_advice_requests_evaluation_id
    ON bjstock.ai_advice_requests (evaluation_id);

-- ---------------------------------------------------------------------------
-- ai_advice_results
-- ---------------------------------------------------------------------------
CREATE TABLE bjstock.ai_advice_results (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id              BIGINT NOT NULL,
    recommendation          TEXT NOT NULL,
    confidence              NUMERIC(6, 4),
    summary                 TEXT,
    reasoning_summary       TEXT,
    risk_notes              TEXT,
    raw_response            TEXT,
    used_in_decision        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_advice_results_request
        FOREIGN KEY (request_id)
        REFERENCES bjstock.ai_advice_requests (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_ai_advice_results_recommendation
        CHECK (recommendation IN ('BUY', 'HOLD', 'SELL', 'NO_OPINION')),
    CONSTRAINT ck_ai_advice_results_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

COMMENT ON TABLE bjstock.ai_advice_results IS
    'AI advisory output. Not an execution instruction. reasoning_summary is user-facing only.';
COMMENT ON COLUMN bjstock.ai_advice_results.raw_response IS
    'Serialized TEXT. Do not treat chain-of-thought as a required stored field.';
COMMENT ON COLUMN bjstock.ai_advice_results.used_in_decision IS
    'Whether this advice was recorded alongside the decision. AI still does not place orders.';

CREATE INDEX idx_ai_advice_results_request_id
    ON bjstock.ai_advice_results (request_id);
