-- BJStock Phase 6 — virtual account cash ledger and order status for pending fills
-- Does not modify 0001–0004 bodies; only extends schema.

SET search_path TO bjstock, public;

-- Pending next-day open fills need an explicit order status.
ALTER TABLE bjstock.orders
    DROP CONSTRAINT ck_orders_status;

ALTER TABLE bjstock.orders
    ADD CONSTRAINT ck_orders_status
        CHECK (status IN (
            'CREATED',
            'PENDING_EXECUTION',
            'VIRTUAL_FILLED',
            'CANCELLED',
            'REJECTED'
        ));

-- Pending BUY quantity is unknown until next open; REJECTED may record quantity 0.
ALTER TABLE bjstock.orders
    DROP CONSTRAINT ck_orders_quantity_positive;

ALTER TABLE bjstock.orders
    ADD CONSTRAINT ck_orders_quantity_nonneg
        CHECK (quantity >= 0);

CREATE TABLE bjstock.cash_ledger (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id     BIGINT NOT NULL,
    event_type          TEXT NOT NULL,
    amount              NUMERIC(20, 4) NOT NULL,
    balance_after       NUMERIC(20, 4) NOT NULL,
    reference_type      TEXT,
    reference_id        BIGINT,
    event_date          DATE NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cash_ledger_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_cash_ledger_event_type
        CHECK (event_type IN (
            'INITIAL_DEPOSIT',
            'BUY',
            'SELL',
            'COMMISSION',
            'TAX',
            'ADJUSTMENT'
        )),
    CONSTRAINT ck_cash_ledger_balance_after_nonneg
        CHECK (balance_after >= 0),
    CONSTRAINT ck_cash_ledger_reference_type_not_empty
        CHECK (reference_type IS NULL OR TRIM(reference_type) <> '')
);

COMMENT ON TABLE bjstock.cash_ledger IS
    'Append-only virtual cash ledger per strategy_run. Current cash = latest balance_after.';
COMMENT ON COLUMN bjstock.cash_ledger.amount IS
    'Signed cash delta in KRW. BUY/COMMISSION/TAX are negative; SELL/INITIAL_DEPOSIT positive.';
COMMENT ON COLUMN bjstock.cash_ledger.balance_after IS
    'Running cash after this event. Must never be negative.';
COMMENT ON COLUMN bjstock.cash_ledger.event_date IS
    'Market/trading date of the cash event (not wall-clock insert day).';

CREATE UNIQUE INDEX uq_cash_ledger_initial_deposit
    ON bjstock.cash_ledger (strategy_run_id)
    WHERE event_type = 'INITIAL_DEPOSIT';

CREATE INDEX idx_cash_ledger_run_created
    ON bjstock.cash_ledger (strategy_run_id, id);

CREATE INDEX idx_cash_ledger_run_event_date
    ON bjstock.cash_ledger (strategy_run_id, event_date);
