-- BJStock Phase 6.1 — immutable paper trading policy snapshot per strategy run
-- Does not modify 0001–0005 bodies.

SET search_path TO bjstock, public;

CREATE TABLE bjstock.paper_trading_policies (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id             BIGINT NOT NULL,
    policy_version              TEXT NOT NULL,
    buy_allocation_rate         NUMERIC(8, 6) NOT NULL,
    commission_rate             NUMERIC(8, 6) NOT NULL,
    sell_tax_rate               NUMERIC(8, 6) NOT NULL,
    slippage_bps                INTEGER NOT NULL,
    execution_price_policy      TEXT NOT NULL,
    additional_buy_policy       TEXT NOT NULL,
    sell_policy                 TEXT NOT NULL,
    short_selling_allowed       BOOLEAN NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_paper_trading_policies_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_paper_trading_policies_strategy_run
        UNIQUE (strategy_run_id),
    CONSTRAINT ck_paper_trading_policies_policy_version_not_empty
        CHECK (TRIM(policy_version) <> ''),
    CONSTRAINT ck_paper_trading_policies_buy_allocation_rate
        CHECK (buy_allocation_rate > 0 AND buy_allocation_rate <= 1),
    CONSTRAINT ck_paper_trading_policies_commission_rate
        CHECK (commission_rate >= 0 AND commission_rate <= 1),
    CONSTRAINT ck_paper_trading_policies_sell_tax_rate
        CHECK (sell_tax_rate >= 0 AND sell_tax_rate <= 1),
    CONSTRAINT ck_paper_trading_policies_slippage_bps
        CHECK (slippage_bps >= 0),
    CONSTRAINT ck_paper_trading_policies_execution_price_policy
        CHECK (execution_price_policy IN ('NEXT_TRADING_DAY_OPEN')),
    CONSTRAINT ck_paper_trading_policies_additional_buy_policy
        CHECK (additional_buy_policy IN ('DISALLOW')),
    CONSTRAINT ck_paper_trading_policies_sell_policy
        CHECK (sell_policy IN ('FULL_POSITION')),
    CONSTRAINT ck_paper_trading_policies_short_selling_disallowed
        CHECK (short_selling_allowed = FALSE)
);

COMMENT ON TABLE bjstock.paper_trading_policies IS
    'Immutable paper-trading policy snapshot. One row per strategy_run. Commission/tax are SIMULATION ASSUMPTION rates, not legal/broker quotes.';
COMMENT ON COLUMN bjstock.paper_trading_policies.buy_allocation_rate IS
    'Fraction of current cash used for a BUY (e.g. 0.10 = 10%). NUMERIC(8,6) ↔ Room Long * WEIGHT_FACTOR.';
COMMENT ON COLUMN bjstock.paper_trading_policies.commission_rate IS
    'SIMULATION ASSUMPTION commission rate on gross.';
COMMENT ON COLUMN bjstock.paper_trading_policies.sell_tax_rate IS
    'SIMULATION ASSUMPTION sell tax rate on gross.';

CREATE INDEX idx_paper_trading_policies_run
    ON bjstock.paper_trading_policies (strategy_run_id);

-- Backfill Phase 6 baseline v1 for any existing runs (none expected in fresh labs).
INSERT INTO bjstock.paper_trading_policies (
    strategy_run_id,
    policy_version,
    buy_allocation_rate,
    commission_rate,
    sell_tax_rate,
    slippage_bps,
    execution_price_policy,
    additional_buy_policy,
    sell_policy,
    short_selling_allowed
)
SELECT
    r.id,
    'v1',
    0.100000,
    0.000150,
    0.002000,
    0,
    'NEXT_TRADING_DAY_OPEN',
    'DISALLOW',
    'FULL_POSITION',
    FALSE
FROM bjstock.strategy_runs r
WHERE NOT EXISTS (
    SELECT 1 FROM bjstock.paper_trading_policies p WHERE p.strategy_run_id = r.id
);
