-- BJStock Phase 9 — Forward Test Orchestration
-- Does not modify 0001–0006 bodies.

SET search_path TO bjstock, public;

CREATE TABLE bjstock.strategy_run_instruments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id     BIGINT NOT NULL,
    instrument_id       BIGINT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_strategy_run_instruments_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_strategy_run_instruments_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES bjstock.instruments (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_strategy_run_instruments_run_instrument
        UNIQUE (strategy_run_id, instrument_id)
);

COMMENT ON TABLE bjstock.strategy_run_instruments IS
    'Forward-test universe snapshot per strategy run. Immutable after READY.';

CREATE INDEX idx_strategy_run_instruments_run
    ON bjstock.strategy_run_instruments (strategy_run_id);

CREATE INDEX idx_strategy_run_instruments_instrument
    ON bjstock.strategy_run_instruments (instrument_id);

CREATE TABLE bjstock.forward_test_cycles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id     BIGINT NOT NULL,
    market_date         DATE NOT NULL,
    status              TEXT NOT NULL,
    current_stage       TEXT NOT NULL,
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    error_code          TEXT,
    error_message       TEXT,
    retryable           BOOLEAN NOT NULL DEFAULT FALSE,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_forward_test_cycles_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_forward_test_cycles_run_date
        UNIQUE (strategy_run_id, market_date),
    CONSTRAINT ck_forward_test_cycles_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETE', 'FAILED')),
    CONSTRAINT ck_forward_test_cycles_stage
        CHECK (current_stage IN (
            'PENDING_FILLS',
            'FACTORS',
            'EVALUATIONS',
            'ORDER_CREATION',
            'SNAPSHOT',
            'COMPLETE'
        )),
    CONSTRAINT ck_forward_test_cycles_attempt_count
        CHECK (attempt_count >= 0)
);

COMMENT ON TABLE bjstock.forward_test_cycles IS
    'One market-date processing attempt for one strategy run. error_message must never contain secrets.';

CREATE INDEX idx_forward_test_cycles_run_date
    ON bjstock.forward_test_cycles (strategy_run_id, market_date);

CREATE INDEX idx_forward_test_cycles_run_status
    ON bjstock.forward_test_cycles (strategy_run_id, status);
