-- BJStock Phase 9.1 — Themes, Signal Rules & Audit Logging
-- Does not modify 0001–0007 bodies.

SET search_path TO bjstock, public;

CREATE TABLE bjstock.themes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    description     TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_themes_name UNIQUE (name),
    CONSTRAINT ck_themes_name_nonempty CHECK (length(btrim(name)) > 0)
);

COMMENT ON TABLE bjstock.themes IS
    'User watch themes (interest baskets). Changes do not mutate Forward Test universes.';

CREATE TABLE bjstock.theme_instruments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_id        BIGINT NOT NULL,
    instrument_id   BIGINT NOT NULL,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_theme_instruments_theme
        FOREIGN KEY (theme_id) REFERENCES bjstock.themes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_theme_instruments_instrument
        FOREIGN KEY (instrument_id) REFERENCES bjstock.instruments (id) ON DELETE RESTRICT,
    CONSTRAINT uq_theme_instruments_theme_instrument
        UNIQUE (theme_id, instrument_id)
);

CREATE INDEX idx_theme_instruments_theme ON bjstock.theme_instruments (theme_id);
CREATE INDEX idx_theme_instruments_instrument ON bjstock.theme_instruments (instrument_id);

CREATE TABLE bjstock.strategy_signal_rules (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_version_id     BIGINT NOT NULL,
    rule_code               TEXT NOT NULL,
    metric_code             TEXT NOT NULL,
    operator                TEXT NOT NULL,
    threshold_value         TEXT NOT NULL,
    action                  TEXT NOT NULL,
    priority                INTEGER NOT NULL,
    enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
    rule_version            TEXT NOT NULL DEFAULT 'v1',
    description             TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_strategy_signal_rules_version
        FOREIGN KEY (strategy_version_id)
        REFERENCES bjstock.strategy_versions (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_strategy_signal_rules_version_code
        UNIQUE (strategy_version_id, rule_code),
    CONSTRAINT ck_strategy_signal_rules_metric
        CHECK (metric_code IN ('DAILY_CHANGE_PCT')),
    CONSTRAINT ck_strategy_signal_rules_operator
        CHECK (operator IN ('GTE', 'LTE')),
    CONSTRAINT ck_strategy_signal_rules_action
        CHECK (action IN ('BUY', 'SELL')),
    CONSTRAINT ck_strategy_signal_rules_priority
        CHECK (priority >= 0)
);

COMMENT ON TABLE bjstock.strategy_signal_rules IS
    'Hard signal rules pinned to a strategy version. Immutable after ACTIVE.';

CREATE INDEX idx_strategy_signal_rules_version
    ON bjstock.strategy_signal_rules (strategy_version_id);

CREATE TABLE bjstock.trade_audit_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_run_id     BIGINT NOT NULL,
    instrument_id       BIGINT,
    evaluation_id       BIGINT,
    order_id            BIGINT,
    execution_id        BIGINT,
    market_date         DATE,
    event_type          TEXT NOT NULL,
    decision_source     TEXT,
    rule_id             BIGINT,
    reason_code         TEXT,
    reason_text         TEXT,
    metric_code         TEXT,
    observed_value      TEXT,
    threshold_value     TEXT,
    event_key           TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trade_audit_logs_run
        FOREIGN KEY (strategy_run_id)
        REFERENCES bjstock.strategy_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_trade_audit_logs_event_key UNIQUE (event_key),
    CONSTRAINT ck_trade_audit_logs_event_type CHECK (event_type IN (
        'RULE_TRIGGERED',
        'EVALUATION_DECIDED',
        'ORDER_CREATED',
        'ORDER_SKIPPED',
        'ORDER_REJECTED',
        'ORDER_CANCELLED',
        'EXECUTION_FILLED'
    )),
    CONSTRAINT ck_trade_audit_logs_decision_source CHECK (
        decision_source IS NULL OR decision_source IN ('SIGNAL_RULE', 'FACTOR_STRATEGY')
    )
);

COMMENT ON TABLE bjstock.trade_audit_logs IS
    'Append-only human-readable trade timeline. Not the transaction source of truth; never auto-delete.';

CREATE INDEX idx_trade_audit_logs_run_date
    ON bjstock.trade_audit_logs (strategy_run_id, market_date);

CREATE INDEX idx_trade_audit_logs_run_created
    ON bjstock.trade_audit_logs (strategy_run_id, created_at);

CREATE TABLE bjstock.api_error_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider            TEXT NOT NULL,
    operation           TEXT NOT NULL,
    error_type          TEXT NOT NULL,
    http_status         INTEGER,
    business_code       TEXT,
    safe_message        TEXT NOT NULL,
    retryable           BOOLEAN NOT NULL DEFAULT FALSE,
    strategy_run_id     BIGINT,
    forward_cycle_id    BIGINT,
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_api_error_logs_provider CHECK (provider IN ('KIS')),
    CONSTRAINT ck_api_error_logs_error_type CHECK (error_type IN (
        'NETWORK_TIMEOUT',
        'HTTP_ERROR',
        'AUTH_ERROR',
        'KIS_BUSINESS_ERROR',
        'MALFORMED_RESPONSE',
        'MASTER_DOWNLOAD_ERROR'
    ))
);

COMMENT ON TABLE bjstock.api_error_logs IS
    'Diagnostics-only API errors. Rolling 7-day retention. Never store secrets/tokens/bodies.';

CREATE INDEX idx_api_error_logs_occurred
    ON bjstock.api_error_logs (occurred_at);
