-- BJStock Phase 11 — Operational Reliability Foundation
-- Does not modify 0001–0008 bodies.
-- See docs/150_OPERATIONAL_RELIABILITY_STANDARD.md

SET search_path TO bjstock, public;

CREATE TABLE bjstock.forward_operations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_key       TEXT NOT NULL,
    trigger             TEXT NOT NULL,
    work_id             TEXT,
    work_attempt        INTEGER,
    through_date        DATE NOT NULL,
    status              TEXT NOT NULL,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at         TIMESTAMPTZ,
    final_code          TEXT,
    safe_message        TEXT,
    runs_considered     INTEGER NOT NULL DEFAULT 0,
    runs_processed      INTEGER NOT NULL DEFAULT 0,
    runs_skipped        INTEGER NOT NULL DEFAULT 0,
    cycles_completed    INTEGER NOT NULL DEFAULT 0,
    cycles_failed       INTEGER NOT NULL DEFAULT 0,
    elapsed_ms          BIGINT,
    CONSTRAINT uq_forward_operations_operation_key UNIQUE (operation_key),
    CONSTRAINT ck_forward_operations_trigger CHECK (trigger IN ('MANUAL', 'WORKER')),
    CONSTRAINT ck_forward_operations_status CHECK (status IN (
        'RUNNING',
        'SUCCEEDED',
        'NO_OP',
        'PARTIAL',
        'BLOCKED',
        'FAILED'
    )),
    CONSTRAINT ck_forward_operations_worker_identity CHECK (
        (trigger = 'WORKER' AND work_id IS NOT NULL AND work_attempt IS NOT NULL)
        OR (trigger = 'MANUAL' AND work_id IS NULL AND work_attempt IS NULL)
    ),
    CONSTRAINT ck_forward_operations_finished_consistency CHECK (
        (status = 'RUNNING') = (finished_at IS NULL)
    ),
    CONSTRAINT ck_forward_operations_counts_nonnegative CHECK (
        runs_considered >= 0 AND runs_processed >= 0 AND runs_skipped >= 0
        AND cycles_completed >= 0 AND cycles_failed >= 0
    ),
    CONSTRAINT ck_forward_operations_work_attempt_nonnegative CHECK (
        work_attempt IS NULL OR work_attempt >= 0
    ),
    CONSTRAINT ck_forward_operations_elapsed_nonnegative CHECK (
        elapsed_ms IS NULL OR elapsed_ms >= 0
    )
);

COMMENT ON TABLE bjstock.forward_operations IS
    'One row per Forward Test invocation (MANUAL / WORKER). Operational evidence, not financial source of truth.';

CREATE INDEX idx_forward_operations_started ON bjstock.forward_operations (started_at);
CREATE INDEX idx_forward_operations_status ON bjstock.forward_operations (status);

CREATE TABLE bjstock.operational_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key           TEXT NOT NULL,
    operation_id        BIGINT,
    run_id              BIGINT,
    cycle_id            BIGINT,
    instrument_id       BIGINT,
    market_date         DATE,
    event_type          TEXT NOT NULL,
    result              TEXT,
    reason_code         TEXT,
    safe_message        TEXT,
    elapsed_ms          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_operational_events_operation
        FOREIGN KEY (operation_id)
        REFERENCES bjstock.forward_operations (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_operational_events_event_key UNIQUE (event_key),
    CONSTRAINT ck_operational_events_event_type CHECK (event_type IN (
        'OPERATION_STARTED',
        'OPERATION_FINISHED',
        'MARKET_SYNC_RESULT',
        'RUN_RESULT',
        'CYCLE_STARTED',
        'CYCLE_FINISHED',
        'WORKER_SCHEDULE_CHANGED'
    )),
    CONSTRAINT ck_operational_events_operation_required CHECK (
        operation_id IS NOT NULL OR event_type = 'WORKER_SCHEDULE_CHANGED'
    ),
    CONSTRAINT ck_operational_events_elapsed_nonnegative CHECK (
        elapsed_ms IS NULL OR elapsed_ms >= 0
    )
);

COMMENT ON TABLE bjstock.operational_events IS
    'Append-only operational evidence. Idempotent by event_key. No raw payloads, headers, bodies, or secrets.';

COMMENT ON COLUMN bjstock.operational_events.run_id IS
    'Soft reference to strategy_runs.id (no FK: log lifecycle must not couple to domain tables).';

CREATE INDEX idx_operational_events_operation ON bjstock.operational_events (operation_id);
CREATE INDEX idx_operational_events_run_created ON bjstock.operational_events (run_id, created_at);
CREATE INDEX idx_operational_events_created ON bjstock.operational_events (created_at);

ALTER TABLE bjstock.trade_audit_logs ADD COLUMN operation_id BIGINT;

COMMENT ON COLUMN bjstock.trade_audit_logs.operation_id IS
    'Nullable soft reference to forward_operations.id. NULL for pre-Phase-11 rows. No FK by design.';

CREATE INDEX idx_trade_audit_logs_operation ON bjstock.trade_audit_logs (operation_id);

ALTER TABLE bjstock.api_error_logs ADD COLUMN operation_id BIGINT;

COMMENT ON COLUMN bjstock.api_error_logs.operation_id IS
    'Nullable soft reference to forward_operations.id. NULL for pre-Phase-11 rows. No FK by design.';

CREATE INDEX idx_api_error_logs_operation ON bjstock.api_error_logs (operation_id);
